const test = require('tape');
const { convertToSwedishCardinalNumber } = require('./dist');

test('convertToSwedishCardinalNumber', assert => {
  assert.equal(convertToSwedishCardinalNumber(0), 'noll', 'noll');
  assert.equal(convertToSwedishCardinalNumber(1), 'en', 'en');
  assert.equal(convertToSwedishCardinalNumber(2), 'två', 'två');
  assert.equal(convertToSwedishCardinalNumber(3), 'tre', 'tre');
  assert.equal(convertToSwedishCardinalNumber(4), 'fyra', 'fyra');
  assert.equal(convertToSwedishCardinalNumber(5), 'fem', 'fem');
  assert.equal(convertToSwedishCardinalNumber(6), 'sex', 'sex');
  assert.equal(convertToSwedishCardinalNumber(7), 'sju', 'sju');
  assert.equal(convertToSwedishCardinalNumber(8), 'åtta', 'åtta');
  assert.equal(convertToSwedishCardinalNumber(9), 'nio', 'nio');
  assert.equal(convertToSwedishCardinalNumber(10), 'tio', 'tio');
  assert.equal(convertToSwedishCardinalNumber(11), 'elva', 'elva');
  assert.equal(convertToSwedishCardinalNumber(12), 'tolv', 'tolv');
  assert.equal(convertToSwedishCardinalNumber(13), 'tretton', 'tretton');
  assert.equal(convertToSwedishCardinalNumber(14), 'fjorton', 'fjorton');
  assert.equal(convertToSwedishCardinalNumber(15), 'femton', 'femton');
  assert.equal(convertToSwedishCardinalNumber(16), 'sexton', 'sexton');
  assert.equal(convertToSwedishCardinalNumber(17), 'sjutton', 'sjutton');
  assert.equal(convertToSwedishCardinalNumber(18), 'arton', 'arton');
  assert.equal(convertToSwedishCardinalNumber(19), 'nitton', 'nitton');
  assert.equal(convertToSwedishCardinalNumber(20), 'tjugo', 'tjugo');
  assert.equal(convertToSwedishCardinalNumber(21), 'tjugo en', 'tjugo en');
  assert.equal(convertToSwedishCardinalNumber(22), 'tjugo två', 'tjugo två');
  assert.equal(convertToSwedishCardinalNumber(23), 'tjugo tre', 'tjugo tre');
  assert.equal(convertToSwedishCardinalNumber(24), 'tjugo fyra', 'tjugo fyra');
  assert.equal(convertToSwedishCardinalNumber(25), 'tjugo fem', 'tjugo fem');
  assert.equal(convertToSwedishCardinalNumber(26), 'tjugo sex', 'tjugo sex');
  assert.equal(convertToSwedishCardinalNumber(27), 'tjugo sju', 'tjugo sju');
  assert.equal(convertToSwedishCardinalNumber(28), 'tjugo åtta', 'tjugo åtta');
  assert.equal(convertToSwedishCardinalNumber(29), 'tjugo nio', 'tjugo nio');
  assert.equal(convertToSwedishCardinalNumber(31), 'trettio en', 'trettio en');
  assert.equal(convertToSwedishCardinalNumber(42), 'fyrtio två', 'fyrtio två');
  assert.equal(convertToSwedishCardinalNumber(53), 'femtio tre', 'femtio tre');
  assert.equal(convertToSwedishCardinalNumber(64), 'sextio fyra', 'sextio fyra');
  assert.equal(convertToSwedishCardinalNumber(75), 'sjuttio fem', 'sjuttio fem');
  assert.equal(convertToSwedishCardinalNumber(86), 'åttio sex', 'åttio sex');
  assert.equal(convertToSwedishCardinalNumber(97), 'nittio sju', 'nittio sju');
  assert.equal(convertToSwedishCardinalNumber(100), 'hundra', 'hundra');
  assert.equal(convertToSwedishCardinalNumber(111), 'ett hundra elva', 'ett hundra elva');
  assert.equal(convertToSwedishCardinalNumber(125), 'ett hundra tjugo fem', 'ett hundra tjugo fem');
  assert.equal(convertToSwedishCardinalNumber(167), 'ett hundra sextio sju', 'ett hundra sextio sju');
  assert.equal(convertToSwedishCardinalNumber(199), 'ett hundra nittio nio', 'ett hundra nittio nio');
  assert.equal(convertToSwedishCardinalNumber(200), 'två hundra', 'två hundra');
  assert.equal(convertToSwedishCardinalNumber(211), 'två hundra elva', 'två hundra elva');
  assert.equal(convertToSwedishCardinalNumber(225), 'två hundra tjugo fem', 'två hundra tjugo fem');
  assert.equal(convertToSwedishCardinalNumber(267), 'två hundra sextio sju', 'två hundra sextio sju');
  assert.equal(convertToSwedishCardinalNumber(299), 'två hundra nittio nio', 'två hundra nittio nio');
  assert.equal(convertToSwedishCardinalNumber(1000), 'tusen', 'tusen');
  assert.equal(convertToSwedishCardinalNumber(1200), 'ett tusen två hundra', 'ett tusen två hundra');
  assert.equal(convertToSwedishCardinalNumber(2211), 'två tusen två hundra elva', 'två tusen två hundra elva');
  assert.equal(convertToSwedishCardinalNumber(3225), 'tre tusen två hundra tjugo fem', 'tre tusen två hundra tjugo fem');
  assert.equal(convertToSwedishCardinalNumber(4267), 'fyra tusen två hundra sextio sju', 'fyra tusen två hundra sextio sju');
  assert.equal(convertToSwedishCardinalNumber(5299), 'fem tusen två hundra nittio nio', 'fem tusen två hundra nittio nio');
  assert.equal(convertToSwedishCardinalNumber(15299), 'femton tusen två hundra nittio nio', 'femton tusen två hundra nittio nio');
  assert.equal(convertToSwedishCardinalNumber(35379), 'trettio fem tusen tre hundra sjuttio nio', 'trettio fem tusen tre hundra sjuttio nio');
  assert.equal(convertToSwedishCardinalNumber(135379), 'ett hundra trettio fem tusen tre hundra sjuttio nio', 'ett hundra trettio fem tusen tre hundra sjuttio nio');

  assert.end();
});